config/routes.rb
Rails.application.routes.draw do
  get 'votes/create'
  resources :books do
    resources :votes, only: [:create]
  end

  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To overide, add your own page#index view or change to a new root
  # Visit the start page for Rails UI any time at /railsui/start
  # root action: :index, controller: "railsui/page"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy

  has_many :voters, through: :votes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name
  has_one_attached :avatar

  has_many :books
  has_many :votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper Railsui::ThemeHelper

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :user_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book

  def create
    @vote = @book.votes.new(user: current_user)

    respond_to do |format|
      if @vote.save
        flash.now[:notice] = "Vote casted successfully"
        format.html { redirect_to @book }
        format.turbo_stream
      else
        flash.now[:alert] = "You have already voted for this book"
        format.html { redirect_to @book }
        format.turbo_stream
      end
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_book.html.erb
<article id="<%= dom_id book %>" class="prose dark:prose-invert p-6 rounded-lg border flex items-start gap-6 bg-white shadow-sm">

  <%= render "votes/vote_button", book: book %>

  <div class="flex-1">
    <p class="my-0">
      <%= link_to book.title, book %>
    </p>

    <p class="my-0">
      <%= book.description %>
    </p>
  </div>
</article>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.text_field :user_id, class: "form-input" %>
  </div>

  <div class="flex items-center justify-between flex-wrap">
    <div class="sm:flex-1 sm:mb-0 mb-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>

    <% if form.object.new_record? %>
      <%= link_to "Cancel", books_path, class: "btn btn-light" %>
    <% else %>
      <%= link_to "Cancel", book_path(@book), class: "btn btn-light" %>
    <% end %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b">
    <nav aria-label="breadcrumb" class="my-6 font-medium flex text-slate-500 dark:text-slate-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3">
        <li>
          <%= link_to "Books", books_path, class: "hover:underline hover:text-slate-600 dark:hover:text-slate-400" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-slate-300 dark:text-slate-500">/</span>
          </div>
          <span class="text-primary-600 dark:text-primary-500" aria-current="page">Edit</span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">Edit Book</h1>
      <%= button_to "Delete", @book, method: :delete, class: "btn btn-light", form: { data: { turbo_confirm: "Are you sure?" } } %>
    </div>
  </div>

  <div>
    <%= render "form", book: @book %>
  </div>
</div>

app/views/books/index.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="flex items-center justify-between pb-6 border-b dark:border-slate-700 mb-6">
    <h1 class="text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">Books</h1>
    <div class="flex items-center justify-end">
      <%= link_to "New Book", new_book_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div id="books" class="dark:text-slate-700 mb-10 grid md:grid-cols-2 grid-cols-1 gap-3">
    <%= render @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b">
    <nav aria-label="breadcrumb" class="my-6 font-medium flex text-slate-500 dark:text-slate-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3">
        <li>
          <%= link_to "Books", books_path, class: "hover:underline hover:text-slate-600 dark:hover:text-slate-400" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-slate-300 dark:text-slate-500">/</span>
          </div>
          <span class="text-primary-600 dark:text-primary-500" aria-current="page">New</span>
        </li>
      </ol>
    </nav>
    <h1 class="text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">New Book</h1>
  </div>

  <div>
    <%= render "form", book: @book %>
  </div>
</div>

app/views/books/show.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="pb-6 border-b">
    <nav aria-label="breadcrumb" class="my-6 font-medium flex text-slate-500 dark:text-slate-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3">
        <li>
          <%= link_to "Books", books_path, class: "hover:underline hover:text-slate-600 dark:hover:text-slate-400" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-slate-300 dark:text-slate-500">/</span>
          </div>
          <span class="text-primary-600 dark:text-primary-500" aria-current="page">
            #<%= @book.id %>
          </span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight flex-1">book #<%= @book.id %></h1>
      <%= link_to "Edit", edit_book_path(@book), class: "btn btn-light" %>
    </div>
  </div>
  <%= render @book %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Railsui.config.application_name || "Rails UI " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "data-turbo-track": "reload" %>

    <%= render "shared/fonts" %>
    <%= render "shared/meta" %>
    <%= custom_colors_css %>
    <%= yield :head %>
  </head>

  <body class="font-normal leading-normal text-slate-800 relative selection:bg-primary-500/40 bg-white dark:bg-slate-900 dark:text-slate-100 antialiased">
    <%= render "shared/flash" %>

    <% if content_for(:header).present? %>
      <%= yield :header %>
    <% else %>
      <%= render "shared/nav" %>
    <% end %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Railsui.config.application_name || "Rails UI " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "data-turbo-track": "reload" %>

    <%= render "shared/fonts" %>
    <%= render "shared/meta" %>
    <%= custom_colors_css %>
    <%= yield :head %>
  </head>

  <body class="font-normal leading-normal text-slate-800 relative selection:bg-primary-500/40 bg-white dark:bg-slate-900 dark:text-slate-100 antialiased">
    <%= render "shared/flash" %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
  </body>
</html>

app/views/shared/_email_action.html.erb
<%# locals: (align: "center", url: root_url, action:, theme: "primary", fullwidth: false) %>

<table class="action" align="<%= align %>">
  <tr>
    <td align="<%= align %>">
      <a href="<%= url %>" class="action__link action__link--<%= theme %> <%= fullwidth == true ? "action__link--expanded" : nil %>" target="_blank"><%= action %></a>
      <div itemscope itemtype="http://schema.org/EmailMessage">
        <div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction">
          <link itemprop="target" href="<%= url %>"/>
          <meta itemprop="name" content="<%= action %>"/>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/shared/_email_spacer.html.erb
<table class="spacer">
  <tbody>
    <tr>
      <td height="<%= amount %>" style="font-size:<%= amount %>px;line-height:<%= amount %>px;">&nbsp;</td>
    </tr>
  </tbody>
</table>
x

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
<div class="bg-rose-50 text-rose-700 sm:px-9 sm:py-6 px-6 py-6 rounded-lg mb-6 dark:bg-rose-400/10 dark:border dark:border-rose-400/20 dark:text-rose-50 text-sm" role="alert">
  <div class="flex items-start space-x-4">
    <%= icon "shield-exclamation", classes: "w-6 h-6 text-rose-700 flex-shrink-0", variant: :solid %>
    <div class="flex-1">
      <p class="font-bold"><%= pluralize(resource.errors.count, "error") %> prohibited this post from being saved:</p>
      <ul class="list-disc mt-3 ml-4">
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_flash.html.erb
 <%= turbo_frame_tag "flash" do %>
  <% flash.each do |type, message| %>
    <div data-controller="flash" data-flash-target="toast" class="fixed z-50 top-2 right-2 border rounded-md p-3 shadow-lg opacity-100 translate-x-full transition-transform ease-in-out duration-300 transform <%= type == :alert ? "bg-red-50 border-red-500/50 text-red-800" : "bg-white border-gray-300/90 text-gray-800" %>">
      <div class="flex items-center justify-between gap-4">
        <%= icon "check", classes: "size-4 stroke-primary-500" %>
        <span><%= message %></span>
        <button type="button" data-action="click->flash#dismiss" class="p-1 hover:bg-gray-100/70 flex items-center justify-center rounded-md">
          <%= icon "x-mark", class: "size-4 stroke-current text-gray-600 pointer-events-none" %>
        </button>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_fonts.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

app/views/shared/_footer.html.erb
<footer class="container mx-auto px-4 pb-4">
  <nav role="Utility navigation">
    <ul class="lg:flex items-center justify-center text-center lg:my-6 mb-6 lg:text-base text-lg">
      <li class="py-3 lg:py-0">
        <%= link_to "Product", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <li class="py-3 lg:py-0">
        <%= link_to "Customers", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <li class="py-3 lg:py-0">
        <%= link_to "Features", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <% if page_exists?("pricing") %>
        <li class="py-3 lg:py-0">
          <%= link_to "Pricing", pricing_path, class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
        </li>
      <% end %>
      <% if page_exists?("about") %>
        <li class="py-3 lg:py-0">
          <%= link_to "Company", about_path, class: "px-3 py-2 hover:text-primary-700  dark:hover:text-primary-500" %>
        </li>
      <% end %>
    </ul>
  </nav>

  <ul class="flex items-center justify-center space-x-6 mb-6">
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "facebook", path: "social/facebook.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "twitter", path: "social/twitter.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "linkedin", path: "social/linkedin.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "youtube", path: "social/youtube.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
  </ul>

  <p class="text-center text-slate-600 text-sm">&copy; <%= Railsui.config.application_name %> All Rights Reserved. <%= Railsui.config.theme.humanize %> theme by <a
      href="https://railsui.com" class="underline" target="_blank">Rails UI</a></p>
</footer>

app/views/shared/_meta.html.erb
<%#

Put a favicon.ico or favicon.svg (preferred) in your public/ folder and add favicon_link_tag "favicon.svg" to your layout inside the <head></head> tags.

You may optionally reach for the meta_tags gem as I did below and do this all dynamically.

Below are the recommended tags to include for best discoverability between apps and services. You don't need everything listed to see success but many apps now query open graph tags to find assets and content for link previews so it goes a long way (i.e., Slack, Twitter, Facebook).

Generate icons:
https://redketchup.io/favicon-generator (generate from an image)

Tip: Before generating icons, I typically start with a icon that is atleast 512x512 in size. It can have a transparent background (.png, .svg). Keep it as simple as possible.

Free editor/vector tool:
https://figma.com

Previewing:
https://www.opengraph.xyz/


# Usage:

Title:
Change the title and description tags below to match your own site. The title displays alongside your site name in a given browser tab next to the favicon.

Description:
The description is a good place for one to two sentences describing a page OR what the site is all about. You can tweak this on a per-page basis inside your views or controllers. See the metatags gem documentation on tips for doing so: https://github.com/kpumuk/meta-tags#mirrored-values

Images:
Swap your own images for placeholder ones inside the "assets/images/meta" folder Rails UI copied to your app (jpg, png).
%>

<%= display_meta_tags(
  site: "#{Railsui.config.application_name.parameterize}.com", # <!-- change -->,
  reverse: true,
  viewport: "width=device-width, initial-scale=1",
  title: "CHANGE ME",
  canonical: request.original_url,
  og: {
    title: Railsui.config.application_name,
    type: "website",
    url: request.original_url,
    image: [{
      _: image_url("meta/opengraph.jpg"),
      width: 1200,
      height: 630
    }],
    site_name: "#{Railsui.config.application_name.parameterize}.com", # <!-- change -->
    description: "CHANGE ME",
  },
  twitter: {
    title: :title,
    description: :description,
    card:  "summary",
    image: {
      _: image_url("meta/opengraph-mark.jpg"),
      width:  400,
      height: 400,
    }
  },
  author: Railsui.config.application_name,
  description: "CHANGE ME",
  icon: [
    {
      href: image_url("meta/favicon.svg"),
      sizes: 'any',
      type: "image/svg+xml"
    },
    {
      href: image_url("meta/favicon-16x16.png"),
      sizes: "16x16",
      type: "images/png"
    },
    {
      href: image_url("meta/android-chrome-192x192.png"),
      sizes: '192x192',
      type: "image/png"
    },
    {
      href: image_url("meta/android-chrome-512x512.png"),
      sizes: '512x512',
      type: "image/png"
    },
    {
      href: image_url("meta/apple-touch-icon.png"),
      sizes: '180x180',
      type: "image/png"
    }
  ])
  %>

app/views/shared/_nav.html.erb
<header class="relative dark:bg-slate-900 bg-white dark:border-slate-700" data-controller="nav">
  <%= render "shared/nav_menu" %>
</header>

app/views/shared/_nav_links.html.erb
<li>
  <%= nav_link_to "Books", books_path, class: "nav-link" %>
</li>

app/views/shared/_nav_menu.html.erb
<div class="container mx-auto px-4">
  <div class="lg:flex items-center flex-wrap sm:space-x-2">
    <div class="lg:block flex items-center justify-between">
      <%= link_to root_path, class: "w-12 h-12 flex justify-center" do %>
        <!-- Hound logo -->
        <svg
          class="fill-current w-5 h-auto text-primary-600 hover:text-primary-700 duration-300 transition ease-in-out
          dark:hover:text-primary-500"
          width="39" height="50" viewBox="0 0 39 50" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd"
            d="M8.55264 0C3.82915 0 0 3.82915 0 8.55265V26.1842C0 30.9077 3.82915 34.7368 8.55264 34.7368C13.2761 34.7368 17.1053 30.9077 17.1053 26.1842V8.55264C17.1053 3.82915 13.2761 0 8.55264 0ZM29.6053 0C24.8818 0 21.0527 3.82915 21.0527 8.55264V41.4474C21.0527 46.1709 24.8818 50 29.6053 50C34.3288 50 38.1579 46.1708 38.1579 41.4474V8.55264C38.1579 3.82915 34.3288 0 29.6053 0Z" />
        </svg>
        <span class="sr-only"><%= Railsui.config.application_name %></span>
      <% end %>

      <button
        id="dropdowns-nav-toggle"
        data-action="click->nav#toggle"
        class="lg:hidden block p-1 rounded focus:ring-4 focus:ring-slate-100 active:bg-white group focus:bg-white/50 dark:focus:bg-slate-800 dark:focus:ring-slate-700">
        <div role="none" data-nav-target="menuBars">
          <%= icon "bars-3-center-left", classes: "w-8 h-8 text-slate-600 group-focus:text-primary-600
          dark:text-slate-400 dark:group-focus:text-slate-100" %>
        </div>
        <div role="none" data-nav-target="menuCross" class="hidden">
          <%= icon "x-mark", classes: "w-8 h-8 text-slate-600 group-focus:text-primary-600 dark:text-slate-400 dark:group-focus:text-slate-100" %>
        </div>
      </button>

    </div>
    <div
      id="dropdowns-navigation"
      class="lg:flex-1 lg:block hidden lg:static absolute top-12 left-0 w-full bg-white dark:bg-slate-900 lg:bg-transparent transform origin-top px-4 pb-4 lg:p-0  rounded-b lg:shadow-none shadow-xl z-40 text-base"
      data-nav-target="nav"
      data-transition-enter-active="transition ease-out duration-200"
      data-transition-enter-from="opacity-0 scale-95"
      data-transition-enter-to="opacity-100 scale-100"
      data-transition-leave-from="opacity-100 scale-100"
      data-transition-leave-active="transition ease-in duration-200"
      data-transition-leave-to="opacity-0 scale-95"
    >
      <div
        class="lg:flex-1 lg:flex flex-wrap items-center justify-between lg:text-left text-center">
        <nav role="Primary navigation">
          <ul
            class="lg:flex block items-center flex-wrap space-x-0 lg:space-x-3 lg:text-base  lg:leading-normal leading-relaxed space-y-1 lg:space-y-0 lg:mb-0 mb-2">
            <%= render "shared/nav_links" %>
          </ul>
        </nav>

        <nav role="Secondary navigation">
          <ul class="lg:flex flex-wrap items-center lg:justify-center justify-between lg:space-x-4">
            <% if user_signed_in? %>
              <li class="lg:mt-0 mt-4 flex flex-col items-center relative" data-controller="dropdown">
                <button class="group" type="button" data-action="click->dropdown#toggle click@window->dropdown#hide">
                  <%= image_tag demo_avatar_url(id: rand(1..100).to_s, variant: ["men", "women"].sample), alt: "current profile photo", class: "rounded-full lg:w-10 w-12 lg:h-10 h-12 object-cover border-2 border-transparent group-hover:border-primary-600 transition duration-300 ease-in-out" %>
                </button>

                <div class="hidden transition transform origin-to-right lg:absolute right-0 top-10 bg-white rounded-lg lg:shadow-xl lg:shadow-slate-900/10 lg:border border-slate-200 lg:min-w-[200px] z-50 py-1 divide-y lg:w-auto w-full lg:text-sm dark:bg-slate-700 dark:shadow-slate-900/50 dark:border-slate-500/60 text-base font-medium text-slate-600 dark:text-slate-200 dark:divide-gray-600" data-dropdown-target="menu"
              data-transition-enter-from="opacity-0 scale-95"
              data-transition-enter-to="opacity-100 scale-100"
              data-transition-leave-from="opacity-100 scale-100"
              data-transition-leave-to="opacity-0 scale-95">
                  <div role="none">
                    <%= link_to "Edit account", edit_user_registration_path, class: "px-4 py-2 lg:py-[.4rem] hover:text-primary-600 dark:hover:text-primary-400 block", data: { turbo: false } %>
                  </div>
                  <div role="none">
                    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "px-4 py-2 lg:py-[.4rem] hover:text-primary-600 dark:hover:text-primary-400 block w-full lg:!text-left !text-center", data: { turbo: false  } %>
                  </div>
                </div>
              </li>
            <% else %>
              <li class="w-full lg:w-auto lg:mb-0 col-span-2 mb-2">
                <%= link_to "Sign in", new_user_session_path, class: "btn btn-transparent lg:w-auto w-full", data: { turbo: false } %>
              </li>
              <li class="lg:pl-3 w-full lg:w-auto col-span-2">
                <%= link_to "Sign up", new_user_registration_path, class: "btn btn-dark lg:w-auto w-full", data: { turbo: false } %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/votes/_vote_button.html.erb
<% if user_signed_in? %>
  <%= turbo_frame_tag "#{dom_id(book)}_vote_button" do %>
    <% unless book.votes.exists?(user: current_user) %>
      <%= button_to book_votes_path(book), class: "btn btn-white !flex-col" do %>
        <%= icon "arrow-up", classes: "size-3" %>
        <span><%= book.votes.size %></span>
      <% end %>
    <% else %>
      <button class="btn btn-white !flex-col disabled:opacity-70 disabled:pointer-events-none disabled:bg-gray-100 disabled:shadow-none" disabled>
        <%= icon "arrow-up", classes: "size-3" %>
        <span><%= book.votes.size %></span>
      </button>
    <% end %>
  <% end %>
<% else %>

  <%= link_to new_user_session_path, class: "btn btn-white !flex-col" do %>
    <%= icon "arrow-up", classes: "size-3" %>
    <span><%= book.votes.size %></span>
  <% end %>
<% end %>